apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/argoproj/argo-rollouts/manifests/cluster-install/?ref=v1.3.1
- github.com/argoproj/argo-rollouts/manifests/dashboard-install/?ref=v1.3.1
